import { Routes } from '@angular/router';
import { BattleshipGamePlayComponent } from './battleship-game-play/battleship-game-play.component';
import { BattleshipGameComponent } from './battleship-game/battleship-game.component';
import { circuitGameComponent } from './circuit-game/circuit-game.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { GameInviteAcceptComponent } from './game-invite-accept/game-invite-accept.component';
import { HashGeneratorComponent } from './hash-generator/hash-generator.component';
import { PasswordGeneratorComponent } from './password-generator/password-generator.component';
import { QrCodeGeneratorComponent } from './qr-code-generator/qr-code-generator.component';
import { SnakeGameComponent } from './snake-game/snake-game.component';
import { TimeConverterComponent } from './time-converter/time-converter.component';
import { UuidGeneratorComponent } from './uuid-generator/uuid-generator.component';
import { SecretMessageGenerateComponent } from './secret-message-generate/secret-message-generate.component';
import { SecretMessageReadComponent } from './secret-message-read/secret-message-read.component';

export const routes: Routes = [
  { path: '', component: DashboardComponent },
  { path: 'time-converter', component: TimeConverterComponent },
  { path: 'password-generator', component: PasswordGeneratorComponent },
  { path: 'hash-generator', component: HashGeneratorComponent },
  { path: 'qr-code-generator', component: QrCodeGeneratorComponent },
  { path: 'uuid-generator', component: UuidGeneratorComponent },
  { path: 'circuit-game', component: circuitGameComponent },
  { path: 'snake-game', component: SnakeGameComponent },
  { path: 'game-invite-accept', component: GameInviteAcceptComponent },
  { path: 'battleship-game', component: BattleshipGameComponent },
  { path: 'battleship-game-play', component: BattleshipGamePlayComponent },
  { path: 'secret-message', component: SecretMessageGenerateComponent },
  { path: 'secret-message-read', component: SecretMessageReadComponent },
  { path: '**', redirectTo: '' },
];
