identifier: m791m3jfo8i3cec4
appPort: 1864
staticPort: 1668
reloadPort: 2667
hostName: localhost
projectName: nisix-utilities
homeFolder: /home/admir/Desktop/ins/projects/nisix-utilities-fe
distFolder: ./dist/nisix-utilities/browser
outDir: >-
  /home/admir/Desktop/ins/projects/nisix-utilities-fe/dist/nisix-utilities/static
handle404: ''
allowErrorCollect: false
